live_config_reload = true
[window]
decorations = "None"
decorations_theme_variant = "Dark"
opacity = 0.8
[font]
normal = { family = "FiraMono Nerd Font Mono", style = "Regular" }
bold = { family = "FiraMono Nerd Font Mono", style = "Bold" }
italic = { family = "FiraMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "FiraMono Nerd Font Mono", style = "Bold Italic" }
size = 12
[colors]
transparent_background_colors = true
# Default colors
#[colors.primary]
#background = '#080a0f'
#foreground = '#d8d8d8'
#[colors.normal]
#black = "#1E0528"
#blue = "#550068"
#cyan = "#8300a0"
#green = "#05CB0D"
#magenta = "#8991BB"
#red = "#00D9E9"
#white = "#FFEEFF"
#yellow = "#955AE7"
#purple = "#ffbd5e"
#[colors.bright]
#black = "#320F55"
#blue = "#550068"
#cyan = "#B900B1"
#green = "#05CB0D"
#magenta = "#8991BB"
#red = "#00D9E9"
#white = "#F8C0FF"
#yellow = "#955AE7"
import = ["./cyberdream.toml"]
