#!/usr/bin/env zsh

export DOTFILES=$HOME/dotfiles
source $DOTFILES/env

if ! command -v brew &> /dev/null; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew install stow git tmux neovim starship fnm ripgrep fzf gcc

brew install --cask alacritty

brew tap FelixKratz/formulae
brew install sketchybar borders

brew install --cask nikitabobko/tap/aerospace

export PATH="$HOME/.local/share/fnm:$PATH"
fnm install --lts
eval "$(fnm env --use-on-cd --shell zsh)"
npm install -g pnpm

pushd $DOTFILES

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd
