#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonight"

sketchybar --add item battery_spacer_right right \
           --set      battery_spacer_right \
                      background.drawing=off

sketchybar --add item battery right \
                      --set battery  \
                      background.drawing=off \
                      label.color="$LABEL_COLOR" \
                      update_freq=120 \
                      script="$PLUGIN_DIR/battery" \
                      --subscribe battery system_woke power_source_change

sketchybar --add item battery_spacer_left right \
           --set      battery_spacer_left \
                      background.drawing=off

sketchybar --add bracket battery_bracket battery_spacer_right battery battery_spacer_left \
           --set         battery_bracket \
                         background.corner_radius="$BRACKET_BACKGROUND_CORNER_RADIUS" \
                         background.color="$BRACKET_BACKGROUND_COLOR" \
                         background.border_color="$BRACKET_BACKGROUND_BORDER_COLOR" \
                         background.border_width="$BRACKET_BACKGROUND_BORDER_WIDTH" \
