#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonight"

sketchybar --add item volume_spacer_right right \
           --set      volume_spacer_right \
                      background.drawing=off

sketchybar --add item volume right \
                      --set volume  \
                      script="$PLUGIN_DIR/volume.sh" \
                      icon.drawing=on \
                      background.drawing=off \
                      icon.color="$LABEL_COLOR" \
                      label.padding_left=0 \
                      label.padding_right=0 \
                      --subscribe volume volume_change 

sketchybar --add item volume_spacer_left right \
           --set      volume_spacer_left \
                      background.drawing=off

sketchybar --add bracket volume_bracket volume_spacer_left volume volume_spacer_right\
           --set         volume_bracket \
                         background.corner_radius="$BRACKET_BACKGROUND_CORNER_RADIUS" \
                         background.color="$BRACKET_BACKGROUND_COLOR" \
                         background.border_color="$BRACKET_BACKGROUND_BORDER_COLOR" \
                         background.border_width="$BRACKET_BACKGROUND_BORDER_WIDTH" \
